# Generated by Django 5.2.17 on 2026-09-19 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='класс на момент регистрации')),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seasons.agegroup', verbose_name='возрастная группа')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='seasons.season', verbose_name='сезон')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seasons.track', verbose_name='направление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'участие в сезоне',
                'verbose_name_plural': 'участие в сезонах',
            },
        ),
        migrations.CreateModel(
            name='VenueBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('status', models.CharField(choices=[('booked', 'Записан'), ('confirmed', 'Подтверждён'), ('attended', 'Пришёл'), ('cancelled', 'Отменена')], default='booked', max_length=12, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='participation.registration', verbose_name='участие')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='seasons.stage', verbose_name='этап')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='venues.venue', verbose_name='площадка')),
            ],
            options={
                'verbose_name': 'запись на площадку',
                'verbose_name_plural': 'записи на площадки',
            },
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('user', 'season'), name='unique_registration_per_season'),
        ),
        migrations.AddConstraint(
            model_name='venuebooking',
            constraint=models.UniqueConstraint(fields=('registration', 'stage'), name='one_venue_per_stage'),
        ),
    ]
