# Generated by Django 5.2.17 on 2026-09-19 07:55

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('role', models.CharField(choices=[('participant', 'Участник'), ('organizer', 'Организатор площадки'), ('jury', 'Жюри'), ('admin', 'Администратор')], default='participant', max_length=20, verbose_name='роль')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='e-mail подтверждён')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='класс')),
                ('school', models.CharField(blank=True, max_length=250, verbose_name='школа')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='город')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='регион')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='Telegram')),
                ('consent_given', models.BooleanField(default=False, verbose_name='согласие на обработку ПД')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='дата согласия')),
                ('consent_version', models.CharField(blank=True, max_length=20, verbose_name='версия текста согласия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'анкета участника',
                'verbose_name_plural': 'анкеты участников',
            },
        ),
    ]
