# Generated by Django 5.2.17 on 2026-09-19 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('consent_given', models.BooleanField(default=False, verbose_name='согласие на обработку ПД')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='дата согласия')),
                ('consent_version', models.CharField(blank=True, max_length=20, verbose_name='версия текста согласия')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='отчество')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='должность')),
                ('organization', models.CharField(blank=True, max_length=250, verbose_name='школа или организация')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='город')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='Telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'анкета организатора',
                'verbose_name_plural': 'анкеты организаторов',
            },
        ),
    ]
