# Generated by Django 5.2.17 on 2026-09-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='consent_given',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='consent_given_at',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='consent_version',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='position',
        ),
    ]
