# Generated by Django 5.2.17 on 2026-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_organizerprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='city',
            field=models.CharField(max_length=120, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='region',
            field=models.CharField(max_length=120, verbose_name='регион'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='school',
            field=models.CharField(max_length=250, verbose_name='школа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Участник'), ('organizer', 'Организатор'), ('admin', 'Администратор')], default='participant', max_length=20, verbose_name='роль'),
        ),
    ]
