# Generated by Django 5.2.17 on 2026-09-24 18:47

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jury_becomes_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='doc_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата выдачи'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='doc_issued_by',
            field=models.CharField(blank=True, max_length=300, verbose_name='кем выдан'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='doc_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='серия и номер'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('passport_rf', 'Паспорт РФ'), ('birth_cert', 'Свидетельство о рождении'), ('foreign', 'Документ другой страны')], max_length=20, verbose_name='документ'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата выдачи (представитель)'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_issued_by',
            field=models.CharField(blank=True, max_length=300, verbose_name='кем выдан (представитель)'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='серия и номер (представитель)'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_type',
            field=models.CharField(blank=True, choices=[('passport_rf', 'Паспорт РФ'), ('birth_cert', 'Свидетельство о рождении'), ('foreign', 'Документ другой страны')], max_length=20, verbose_name='документ представителя'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя представителя'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='фамилия представителя'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='отчество представителя'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_reg_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='адрес регистрации (представитель)'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='reg_address',
            field=models.CharField(blank=True, help_text='Как в паспорте, с индексом', max_length=500, verbose_name='адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='region',
            field=models.CharField(blank=True, max_length=120, verbose_name='регион'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='school',
            field=models.CharField(blank=True, max_length=250, verbose_name='школа'),
        ),
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('file', models.FileField(upload_to=apps.accounts.models.consent_upload_path, verbose_name='скан')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='исходное имя')),
                ('for_minor', models.BooleanField(default=True, verbose_name='подписывает представитель')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Что было в анкете в момент загрузки', verbose_name='данные в бланке')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Нужно переслать'), ('outdated', 'Устарело (данные изменены)')], default='pending', max_length=10, verbose_name='статус')),
                ('review_comment', models.TextField(blank=True, help_text='Если просите переслать — что не так. Уйдёт участнику письмом', verbose_name='комментарий участнику')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='когда проверено')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'verbose_name': 'согласие на обработку ПД',
                'verbose_name_plural': 'согласия на обработку ПД',
                'ordering': ['-created_at'],
            },
        ),
    ]
