# Данные представителя на сайте больше не хранятся: он вписывает их в бланк
# согласия от руки. Серия и номер документа — отдельными полями.
# Generated by Django 5.2.17 on 2026-09-24 19:28

from django.db import migrations, models


def split_series(apps, schema_editor):
    """«4510 123456» → серия 4510, номер 123456. Остальное — по последнему пробелу."""
    Profile = apps.get_model("accounts", "ParticipantProfile")
    for profile in Profile.objects.exclude(doc_number=""):
        value = profile.doc_number.strip()
        if " " not in value:
            continue
        series, number = value.rsplit(" ", 1)
        profile.doc_series, profile.doc_number = series.replace(" ", ""), number
        profile.save(update_fields=["doc_series", "doc_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_participant_documents_and_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_issued_at',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_issued_by',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_number',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_type',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_first_name',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_last_name',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_middle_name',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_reg_address',
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='doc_series',
            field=models.CharField(blank=True, max_length=20, verbose_name='серия'),
        ),
        migrations.AlterField(
            model_name='consentdocument',
            name='for_minor',
            field=models.BooleanField(default=True, verbose_name='подписывает и представитель'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='doc_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='номер'),
        ),
        migrations.RunPython(split_series, migrations.RunPython.noop),
    ]
