# Generated by Django 5.2.17 on 2026-09-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_split_document_series_drop_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата выдачи (представитель)'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_issued_by',
            field=models.CharField(blank=True, max_length=300, verbose_name='кем выдан (представитель)'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='номер (представитель)'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_series',
            field=models.CharField(blank=True, max_length=20, verbose_name='серия (представитель)'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_type',
            field=models.CharField(blank=True, choices=[('passport_rf', 'Паспорт РФ'), ('birth_cert', 'Свидетельство о рождении'), ('foreign', 'Документ другой страны')], max_length=20, verbose_name='документ представителя'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя представителя'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='фамилия представителя'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='отчество представителя'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_reg_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='адрес регистрации (представитель)'),
        ),
        migrations.AlterField(
            model_name='consentdocument',
            name='for_minor',
            field=models.BooleanField(default=True, verbose_name='согласие даёт представитель'),
        ),
    ]
