# Generated by Django 5.2.17 on 2026-09-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_parent_data_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='doc_division_code',
            field=models.CharField(blank=True, help_text='Только для паспорта РФ', max_length=7, verbose_name='код подразделения'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='parent_doc_division_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='код подразделения (представитель)'),
        ),
    ]
