# Generated by Django 5.2.17 on 2026-09-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_document_division_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='parent_reg_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='адрес регистрации по паспорту (представитель)'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='reg_address',
            field=models.CharField(blank=True, help_text='Как в паспорте, с индексом', max_length=500, verbose_name='адрес регистрации по паспорту'),
        ),
    ]
