# Generated by Django 5.2.17 on 2026-09-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_registration_address_by_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_division_code',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_issued_at',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_issued_by',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_number',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_series',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_doc_type',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_first_name',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_last_name',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_middle_name',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='parent_reg_address',
        ),
        migrations.AlterField(
            model_name='consentdocument',
            name='for_minor',
            field=models.BooleanField(default=True, verbose_name='согласие даёт родитель'),
        ),
    ]
