# Generated by Django 5.2.17 on 2026-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_parent_data_by_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Как в паспорте или свидетельстве о рождении', max_length=250, verbose_name='место рождения'),
        ),
    ]
