# Generated by Django 5.2.17 on 2026-10-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отметки об ознакомлении'),
        ),
    ]
