# Generated by Django 5.2.17 on 2026-09-19 07:55

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('slug', models.SlugField(unique=True, verbose_name='адрес')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='текст (HTML)')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='показывать в меню')),
                ('menu_order', models.PositiveSmallIntegerField(default=100, verbose_name='порядок в меню')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
                'ordering': ['menu_order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='адрес')),
                ('summary', models.CharField(blank=True, max_length=400, verbose_name='краткое описание')),
                ('body', models.TextField(verbose_name='текст')),
                ('cover', models.ImageField(blank=True, upload_to='news/', verbose_name='картинка')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='seasons.season', verbose_name='сезон')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('slug', models.SlugField(verbose_name='адрес')),
                ('lecturer', models.CharField(blank=True, max_length=150, verbose_name='лектор')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('held_at', models.DateTimeField(blank=True, null=True, verbose_name='дата проведения')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, VK Видео, Rutube', verbose_name='ссылка на видео')),
                ('slides', models.FileField(blank=True, upload_to='lectures/', validators=[apps.core.validators.validate_upload_size], verbose_name='презентация')),
                ('cover', models.ImageField(blank=True, upload_to='lectures/covers/', verbose_name='превью')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='seasons.season', verbose_name='сезон')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seasons.track', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'лекция',
                'verbose_name_plural': 'лекции',
                'ordering': ['-held_at'],
                'constraints': [models.UniqueConstraint(fields=('season', 'slug'), name='unique_lecture_slug_per_season')],
            },
        ),
    ]
