# Generated by Django 5.2.17 on 2026-09-19 08:33

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('kind', models.CharField(choices=[('problems', 'Условия задач'), ('solutions', 'Решения и разборы'), ('data', 'Данные к задачам'), ('code', 'Код и ноутбуки'), ('video', 'Видеоразбор'), ('results', 'Результаты'), ('other', 'Прочее')], default='other', max_length=12, verbose_name='тип')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('problem_number', models.PositiveSmallIntegerField(blank=True, help_text='Если материал относится к одной задаче, а не ко всему туру', null=True, verbose_name='номер задачи')),
                ('file', models.FileField(blank=True, upload_to='archive/%Y/', validators=[apps.core.validators.validate_upload_size], verbose_name='файл')),
                ('external_url', models.URLField(blank=True, help_text='Для больших файлов и видео: Яндекс.Диск, VK Видео', verbose_name='внешняя ссылка')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='размер, байт')),
                ('source_path', models.CharField(blank=True, help_text='Заполняется при импорте, чтобы не задваивать материалы', max_length=500, verbose_name='путь в исходном архиве')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_materials', to='seasons.season', verbose_name='сезон')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_materials', to='seasons.stage', verbose_name='этап')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seasons.track', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'материал архива',
                'verbose_name_plural': 'материалы архива',
                'ordering': ['-season__year', 'order', 'title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_path__gt', '')), fields=('season', 'source_path'), name='unique_archive_source_path')],
            },
        ),
    ]
