# Generated by Django 5.2.17 on 2026-09-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_archivematerial'),
        ('seasons', '0002_alter_stage_options_stage_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, help_text='Скопируйте адрес из строки браузера: ВКонтакте, YouTube или Rutube. Видео будет проигрываться прямо на сайте.', verbose_name='ссылка на видео'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='описание')),
                ('url', models.URLField(verbose_name='ссылка на плейлист')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('season', models.ForeignKey(blank=True, help_text='Пусто — плейлист показывается во всех сезонах', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='seasons.season', verbose_name='сезон')),
            ],
            options={
                'verbose_name': 'плейлист',
                'verbose_name_plural': 'плейлисты',
                'ordering': ['order', 'title'],
            },
        ),
    ]
