# Generated by Django 5.2.17 on 2026-09-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_lecture_video_url_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, help_text='Для YouTube подтягивается автоматически: manage.py fetch_playlist_covers', upload_to='playlists/', verbose_name='превью'),
        ),
    ]
