# Generated by Django 5.2.17 on 2026-09-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_playlist_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на ОДНО видео: ВКонтакте, YouTube или Rutube — скопируйте адрес из строки браузера, видео заиграет прямо на сайте. Ссылка на плейлист не встраивается: для плейлистов есть отдельный раздел.', verbose_name='ссылка на видео'),
        ),
    ]
