# Generated by Django 5.2.17 on 2026-09-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_lecture_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivematerial',
            name='track',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='track',
        ),
    ]
