# Generated by Django 5.2.17 on 2026-09-20 14:25

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_archivematerial_track_remove_lecture_track'),
        ('seasons', '0006_stage_place_alter_stage_short_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('image', models.ImageField(upload_to='photos/%Y/', validators=[apps.core.validators.validate_upload_size], verbose_name='фотография')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='подпись')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('season', models.ForeignKey(blank=True, help_text='Год, с которого снимок. Пусто — без года', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='seasons.season', verbose_name='сезон')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
                'ordering': ['-season__year', 'order', 'pk'],
            },
        ),
    ]
