# Generated by Django 5.2.17 on 2026-09-20 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def publish_flag_to_status(apps, schema_editor):
    """Опубликованные лекции считаем одобренными — иначе они пропадут
    с сайта прямо в момент миграции."""
    Lecture = apps.get_model("content", "Lecture")
    Lecture.objects.filter(is_published=True).update(status="approved")
    Lecture.objects.filter(is_published=False).update(status="draft")


def status_to_publish_flag(apps, schema_editor):
    Lecture = apps.get_model("content", "Lecture")
    Lecture.objects.filter(status="approved").update(is_published=True)
    Lecture.objects.exclude(status="approved").update(is_published=False)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_lectures', to=settings.AUTH_USER_MODEL, verbose_name='кто добавил'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='moderation_comment',
            field=models.TextField(blank=True, help_text='Виден автору, если лекция отклонена', verbose_name='комментарий администратора'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На одобрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='draft', max_length=10, verbose_name='статус'),
        ),
            migrations.RunPython(publish_flag_to_status, status_to_publish_flag),
        migrations.RemoveField(
            model_name='lecture',
            name='is_published',
        ),
    ]
