# Generated by Django 5.2.17 on 2026-09-20 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_lecture_is_published_lecture_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('slug', models.SlugField(unique=True, verbose_name='код')),
                ('title', models.CharField(max_length=120, verbose_name='название')),
                ('section', models.CharField(choices=[('physics', 'Физика'), ('programming', 'Программирование'), ('common', 'Общее')], default='physics', max_length=12, verbose_name='раздел')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='пояснение')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'тема лекций',
                'verbose_name_plural': 'темы лекций',
                'ordering': ['section', 'order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['season__year', 'order', 'pk'], 'verbose_name': 'фотография', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AddField(
            model_name='lecture',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='По ней лекции группируются в архиве', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='content.topic', verbose_name='тема'),
        ),
    ]
