# Generated by Django 5.2.17 on 2026-10-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_consent_dist_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivematerial',
            name='external_url',
            field=models.URLField(blank=True, help_text='Для больших файлов и видео: Яндекс.Диск, VK Видео', max_length=1000, verbose_name='внешняя ссылка'),
        ),
    ]
