# Generated by Django 5.2.17 on 2026-09-19 07:55

import apps.contest.models
import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='номер')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('statement_html', models.TextField(blank=True, verbose_name='условие (текст на странице)')),
                ('statement_pdf', models.FileField(blank=True, help_text='Скомпилированный из LaTeX PDF', upload_to=apps.contest.models.problem_upload_path, validators=[apps.core.validators.validate_upload_size], verbose_name='условие (PDF)')),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='максимальный балл')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Пусто — сразу вместе с этапом', null=True, verbose_name='опубликовать в')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликована')),
                ('solution_pdf', models.FileField(blank=True, upload_to=apps.contest.models.problem_upload_path, validators=[apps.core.validators.validate_upload_size], verbose_name='разбор (PDF)')),
                ('solution_published_at', models.DateTimeField(blank=True, null=True, verbose_name='разбор доступен с')),
                ('age_groups', models.ManyToManyField(blank=True, to='seasons.agegroup', verbose_name='для каких классов')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='seasons.stage', verbose_name='этап')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seasons.track', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['stage', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ProblemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='название')),
                ('file', models.FileField(upload_to=apps.contest.models.problem_upload_path, validators=[apps.core.validators.validate_upload_size], verbose_name='файл')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contest.problem', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'материал к задаче',
                'verbose_name_plural': 'материалы к задачам',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий участника')),
                ('answer', models.CharField(blank=True, help_text='Для задач с числовым ответом', max_length=250, verbose_name='ответ')),
                ('is_latest', models.BooleanField(default=True, verbose_name='последняя попытка')),
                ('is_late', models.BooleanField(default=False, verbose_name='после дедлайна')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.problem', verbose_name='задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'verbose_name': 'решение',
                'verbose_name_plural': 'решения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='балл')),
                ('comment', models.TextField(blank=True, help_text='Виден участнику после публикации результатов', verbose_name='комментарий жюри')),
                ('status', models.CharField(choices=[('new', 'Не проверено'), ('in_review', 'Проверяется'), ('graded', 'Проверено')], default='new', max_length=10, verbose_name='статус')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='проверяющий')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='contest.submission', verbose_name='решение')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('file', models.FileField(upload_to=apps.contest.models.solution_upload_path, validators=[apps.core.validators.validate_solution_file], verbose_name='файл')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contest.submission', verbose_name='решение')),
            ],
            options={
                'verbose_name': 'файл решения',
                'verbose_name_plural': 'файлы решений',
            },
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(fields=('stage', 'number'), name='unique_problem_number_per_stage'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'is_latest'], name='contest_sub_problem_2a75cb_idx'),
        ),
    ]
