# Generated by Django 5.2.17 on 2026-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='age_groups',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='track',
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, help_text='Виден участнику после публикации результатов', verbose_name='комментарий проверяющего'),
        ),
    ]
