# Generated by Django 5.2.17 on 2026-09-20 13:08

import apps.contest.models
import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def publish_flag_to_status(apps, schema_editor):
    """Галочка «опубликована» превращается в статус одобрения.

    Без этого уже заведённые задачи остались бы черновиками и пропали
    бы с сайта в момент миграции.
    """
    Problem = apps.get_model("contest", "Problem")
    Problem.objects.filter(is_published=True).update(status="approved")
    Problem.objects.filter(is_published=False).update(status="draft")


def status_to_publish_flag(apps, schema_editor):
    Problem = apps.get_model("contest", "Problem")
    Problem.objects.filter(status="approved").update(is_published=True)
    Problem.objects.exclude(status="approved").update(is_published=False)


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_problem_age_groups_remove_problem_track_and_more'),
        ('participation', '0002_remove_registration_age_group_and_more'),
        ('venues', '0002_remove_venue_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_problems', to=settings.AUTH_USER_MODEL, verbose_name='автор задачи'),
        ),
        migrations.AddField(
            model_name='problem',
            name='figure',
            field=models.ImageField(blank=True, help_text='Схема или график, показывается прямо под условием', upload_to=apps.contest.models.problem_upload_path, validators=[apps.core.validators.validate_upload_size], verbose_name='рисунок к условию'),
        ),
        migrations.AddField(
            model_name='problem',
            name='figure_caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='подпись к рисунку'),
        ),
        migrations.AddField(
            model_name='problem',
            name='moderation_comment',
            field=models.TextField(blank=True, help_text='Виден автору задачи, если задача отклонена', verbose_name='комментарий администратора'),
        ),
        migrations.AddField(
            model_name='problem',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Кроме автора задачи. Назначает администратор', related_name='reviewed_problems', to=settings.AUTH_USER_MODEL, verbose_name='дополнительные проверяющие'),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На одобрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='draft', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Необязательно. Участникам не показывается', max_digits=6, null=True, verbose_name='максимальный балл'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Пусто — сразу после одобрения', null=True, verbose_name='опубликовать в'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement_html',
            field=models.TextField(blank=True, help_text='Формулы в долларах: $E = mc^2$ в строке, $$...$$ отдельным блоком (LaTeX)', verbose_name='условие'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement_pdf',
            field=models.FileField(blank=True, help_text='Если условие удобнее отдать файлом', upload_to=apps.contest.models.problem_upload_path, validators=[apps.core.validators.validate_upload_size], verbose_name='условие (PDF)'),
        ),
        migrations.RunPython(publish_flag_to_status, status_to_publish_flag),
        migrations.RemoveField(
            model_name='problem',
            name='is_published',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('points', models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — задача не проверена или не сдавалась', max_digits=6, null=True, verbose_name='балл')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_scores', to=settings.AUTH_USER_MODEL, verbose_name='кто внёс')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='contest.problem', verbose_name='задача')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='participation.registration', verbose_name='участие')),
                ('venue', models.ForeignKey(blank=True, help_text='Где писал участник. Пусто — сдавал дистанционно', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='venues.venue', verbose_name='площадка')),
            ],
            options={
                'verbose_name': 'балл за задачу',
                'verbose_name_plural': 'баллы за задачи',
                'ordering': ['problem__number'],
                'constraints': [models.UniqueConstraint(fields=('registration', 'problem'), name='unique_score_per_problem')],
            },
        ),
    ]
