# Generated by Django 5.2.17 on 2026-09-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_remove_problem_is_published_problem_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='исходное имя'),
        ),
    ]
