# Generated by Django 5.2.17 on 2026-09-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_submissionfile_original_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='publish_at',
        ),
    ]
