# Generated by Django 5.2.17 on 2026-09-19 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('slug', models.SlugField(unique=True, verbose_name='код')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('min_grade', models.PositiveSmallIntegerField(verbose_name='класс с')),
                ('max_grade', models.PositiveSmallIntegerField(verbose_name='класс по')),
            ],
            options={
                'verbose_name': 'возрастная группа',
                'verbose_name_plural': 'возрастные группы',
                'ordering': ['min_grade'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('year', models.PositiveSmallIntegerField(help_text='2027 для сезона 2026/27', unique=True, verbose_name='год завершения')),
                ('slug', models.SlugField(help_text='используется в URL: /archive/ao27/', unique=True, verbose_name='адрес')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('accent_color', models.CharField(default='#2f6fed', help_text='HEX, используется в оформлении: #2f6fed', max_length=7, verbose_name='цвет сезона')),
                ('logo', models.ImageField(blank=True, upload_to='seasons/', verbose_name='логотип')),
                ('is_active', models.BooleanField(default=False, help_text='Активным может быть только один сезон — он показывается на главной.', verbose_name='текущий сезон')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликован')),
            ],
            options={
                'verbose_name': 'сезон',
                'verbose_name_plural': 'сезоны',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('slug', models.SlugField(unique=True, verbose_name='код')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'направление',
                'verbose_name_plural': 'направления',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('kind', models.CharField(choices=[('online', 'Дистанционный'), ('offline', 'Очный')], max_length=10, verbose_name='тип')),
                ('slug', models.SlugField(verbose_name='адрес')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('starts_at', models.DateTimeField(verbose_name='начало')),
                ('ends_at', models.DateTimeField(verbose_name='дедлайн')),
                ('results_at', models.DateTimeField(blank=True, null=True, verbose_name='публикация результатов')),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True, verbose_name='запись открывается')),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True, verbose_name='запись закрывается')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликован')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='seasons.season', verbose_name='сезон')),
            ],
            options={
                'verbose_name': 'этап',
                'verbose_name_plural': 'этапы',
                'ordering': ['starts_at'],
                'constraints': [models.UniqueConstraint(fields=('season', 'slug'), name='unique_stage_slug_per_season')],
            },
        ),
    ]
