# Generated by Django 5.2.17 on 2026-09-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order', 'starts_at'], 'verbose_name': 'этап', 'verbose_name_plural': 'этапы'},
        ),
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 — первый отборочный, 2 — второй отборочный, 3 — финал', verbose_name='порядок'),
        ),
        migrations.AddField(
            model_name='stage',
            name='requires_proctoring',
            field=models.BooleanField(default=False, help_text='Работа выполняется под наблюдением через камеру', verbose_name='с прокторингом'),
        ),
        migrations.AddField(
            model_name='stage',
            name='short_note',
            field=models.CharField(blank=True, help_text='Короткая строка под названием этапа: «ноябрь — декабрь»', max_length=120, verbose_name='подпись на схеме'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='kind',
            field=models.CharField(choices=[('online', 'Только дистанционно'), ('offline', 'Только очно'), ('hybrid', 'Дистанционно или на площадке')], max_length=10, verbose_name='формат'),
        ),
    ]
