# Generated by Django 5.2.17 on 2026-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_archivematerial_track_remove_lecture_track'),
        ('contest', '0002_remove_problem_age_groups_remove_problem_track_and_more'),
        ('participation', '0002_remove_registration_age_group_and_more'),
        ('seasons', '0002_alter_stage_options_stage_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgeGroup',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='stage',
            name='is_practice',
            field=models.BooleanField(default=False, help_text='Служебный этап-песочница: не показывается как текущий тур, нужен, чтобы проверить загрузку решений в любой момент', verbose_name='тренировочный'),
        ),
    ]
