# Generated by Django 5.2.17 on 2026-09-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_delete_agegroup_delete_track_stage_is_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='platform_url',
            field=models.URLField(blank=True, help_text='Если тур проходит не на нашем сайте: например, https://exams.mipt.ru для этапа с прокторингом', verbose_name='внешняя платформа'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 — первый отборочный, 2 — второй отборочный, 3 — финал. У равноценных форматов одного тура порядок совпадает: очный и дистанционный первый отбор — это один этап, пройти нужно что-то одно.', verbose_name='порядок'),
        ),
    ]
