# Generated by Django 5.2.17 on 2026-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0005_stage_results_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='place',
            field=models.CharField(blank=True, help_text='Показывается на схеме отдельной строкой: «Кампус МФТИ»', max_length=120, verbose_name='место проведения'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='short_note',
            field=models.CharField(blank=True, help_text='Короткая строка под названием этапа: «19–24 октября»', max_length=120, verbose_name='даты на схеме'),
        ),
    ]
