# Generated by Django 5.2.17 on 2026-09-19 07:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(help_text='Например: Лицей №1580, г. Москва', max_length=250, verbose_name='название площадки')),
                ('short_title', models.CharField(blank=True, max_length=100, verbose_name='короткое название')),
                ('description', models.TextField(blank=True, help_text='Как пройти, какой вход, что взять с собой', verbose_name='описание')),
                ('region', models.CharField(max_length=120, verbose_name='регион')),
                ('city', models.CharField(max_length=120, verbose_name='город')),
                ('address', models.CharField(max_length=300, verbose_name='адрес')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='широта')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='долгота')),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Сколько участников поместится', verbose_name='вместимость')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='draft', max_length=10, verbose_name='статус')),
                ('moderation_comment', models.TextField(blank=True, verbose_name='комментарий модератора')),
                ('is_visible', models.BooleanField(default=True, verbose_name='показывать на карте')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_venues', to=settings.AUTH_USER_MODEL, verbose_name='кто подал заявку')),
                ('managers', models.ManyToManyField(blank=True, help_text='Кто отвечает за эту площадку', related_name='managed_venues', to=settings.AUTH_USER_MODEL, verbose_name='организаторы')),
                ('seasons', models.ManyToManyField(blank=True, related_name='venues', to='seasons.season', verbose_name='сезоны')),
            ],
            options={
                'verbose_name': 'площадка',
                'verbose_name_plural': 'площадки',
                'ordering': ['region', 'city', 'title'],
                'indexes': [models.Index(fields=['status', 'is_visible'], name='venues_venu_status_73a0c8_idx')],
            },
        ),
    ]
