# Generated by Django 5.2.17 on 2026-09-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
    ]
