# Generated by Django 5.2.17 on 2026-09-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_remove_venue_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='contact_telegram',
            field=models.CharField(blank=True, help_text='Например: @ivanov', max_length=64, verbose_name='Telegram'),
        ),
    ]
