# Generated by Django 5.2.17 on 2026-09-19 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('subject', models.CharField(max_length=250, verbose_name='тема письма')),
                ('body', models.TextField(help_text='Можно использовать {{ first_name }} и {{ last_name }} — подставится имя получателя.', verbose_name='текст письма')),
                ('audience', models.CharField(choices=[('all_participants', 'Все зарегистрированные участники'), ('season', 'Участники выбранного сезона'), ('submitted', 'Сдавшие хотя бы одну задачу в сезоне'), ('not_submitted', 'Зарегистрированные, но ничего не сдавшие'), ('venue_booked', 'Записавшиеся на очный тур'), ('organizers', 'Организаторы площадок'), ('jury', 'Жюри')], default='all_participants', max_length=20, verbose_name='кому')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди на отправку'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('failed', 'Ошибка')], default='draft', max_length=10, verbose_name='статус')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='поставлена в очередь')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='отправка завершена')),
                ('last_error', models.TextField(blank=True, verbose_name='последняя ошибка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('season', models.ForeignKey(blank=True, help_text='Нужен для аудиторий, привязанных к сезону.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seasons.season', verbose_name='сезон')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=10, verbose_name='статус')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='mailing.newsletter', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
                'indexes': [models.Index(fields=['newsletter', 'status'], name='mailing_del_newslet_88ebfc_idx')],
                'constraints': [models.UniqueConstraint(fields=('newsletter', 'user'), name='one_delivery_per_user')],
            },
        ),
    ]
