# Generated by Django 5.2.17 on 2026-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='audience',
            field=models.CharField(choices=[('all_participants', 'Все зарегистрированные участники'), ('season', 'Участники выбранного сезона'), ('submitted', 'Сдавшие хотя бы одну задачу в сезоне'), ('not_submitted', 'Зарегистрированные, но ничего не сдавшие'), ('venue_booked', 'Записавшиеся на очный тур'), ('organizers', 'Организаторы')], default='all_participants', max_length=20, verbose_name='кому'),
        ),
    ]
