# Generated by Django 5.2.17 on 2026-09-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_jury_audience_becomes_organizers'),
        ('venues', '0003_venue_contact_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Нужна для рассылки по одной площадке.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='venues.venue', verbose_name='площадка'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='audience',
            field=models.CharField(choices=[('all_participants', 'Все зарегистрированные участники'), ('season', 'Участники выбранного сезона'), ('submitted', 'Сдавшие хотя бы одну задачу в сезоне'), ('not_submitted', 'Зарегистрированные, но ничего не сдавшие'), ('venue_booked', 'Записавшиеся на очный тур'), ('venue', 'Записавшиеся на выбранную площадку'), ('organizers', 'Организаторы')], default='all_participants', max_length=20, verbose_name='кому'),
        ),
    ]
