# Generated by Django 5.2.17 on 2026-10-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_newsletter_venue_alter_newsletter_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='audience',
            field=models.CharField(choices=[('all_participants', 'Все зарегистрированные участники'), ('season', 'Участники выбранного сезона'), ('submitted', 'Сдавшие хотя бы одну задачу в сезоне'), ('not_submitted', 'Зарегистрированные, но ничего не сдавшие'), ('venue_booked', 'Записавшиеся на очный тур'), ('venue', 'Записавшиеся на выбранную площадку'), ('venue_organizers', 'Организаторы выбранной площадки'), ('organizers', 'Все организаторы'), ('admins', 'Администраторы')], default='all_participants', max_length=25, verbose_name='кому'),
        ),
    ]
